name: lighthouse-baseline-rotate

on:
  workflow_dispatch:
    inputs:
      keep:
        description: "Anzahl Snapshots behalten"
        required: false
        default: "5"
  push:
    branches: [ main ]
    paths:
      - 'next-app/docs/lighthouse-baseline-*.json'

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install (prod depth minimal)
        run: npm install --workspaces=false --no-audit --no-fund
      - name: Install next-app deps
        run: cd next-app && npm install --no-audit --no-fund
      - name: Rotate Baselines
        env:
          LH_BASELINE_KEEP: ${{ github.event.inputs.keep || 5 }}
        run: npm --prefix next-app run ci:lh-baseline-rotate
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add next-app/docs/lighthouse-baselines/ next-app/docs/lighthouse-baseline-current.json || true
            git commit -m "chore: rotate lighthouse baselines" || true
          fi
      - name: Push
        if: success()
        run: |
          if [ -n "$(git log origin/main..HEAD)" ]; then
            git push origin HEAD:main
          fi
      - name: Upload Rotation Summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-baseline-rotation
          path: next-app/docs/lighthouse-baselines/rotation-summary.json