name: CI – Performance Gate

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: perf-gate-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  PAGES: '/ /pricing /technology /contact /projects /why-us'
  THRESH_LCP_MS: '3000'
  THRESH_CLS: '0.10'
  THRESH_INP_MS: '200'
  THRESH_TBT_MS: '250'
  MIN_PERF_SCORE: '0.85'
  MIN_A11Y_SCORE: '0.90'
  MIN_SEO_SCORE: '0.90'

jobs:
  perf-gate:
    name: Build + Lighthouse + Threshold Gate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install root deps
        run: npm ci --no-audit --no-fund

      - name: Install next-app deps
        working-directory: next-app
        run: npm ci --no-audit --no-fund || npm install --no-fund --no-audit

      - name: Build (prod)
        working-directory: next-app
        run: npm run build

      - name: Start server
        working-directory: next-app
        run: |
          npm start &
          echo $! > server.pid
          sleep 5

      - name: Wait for port 3000
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 > /dev/null; then echo "Server bereit"; exit 0; fi
            sleep 2
          done
          echo "Server nicht gestartet" >&2
          exit 1

      - name: Lighthouse Baseline
        working-directory: next-app
        run: |
          node scripts/seo/lighthouse-baseline.mjs --base http://localhost:3000 --paths $PAGES || echo "Baseline Script Warnung"

      - name: Diff (falls vorherige Baseline vorhanden)
        working-directory: next-app
        run: |
          if [ -f docs/lighthouse-baseline-prev.json ]; then
            echo "Vorherige Baseline bereits verschoben";
          fi
          if [ -f docs/lighthouse-baseline-current.json ]; then
            cp docs/lighthouse-baseline-current.json docs/lighthouse-baseline-prev.json || true
          fi
          # Nach neuem Lauf wurde current überschrieben
          if [ -f docs/lighthouse-baseline-prev.json ] && [ -f docs/lighthouse-baseline-current.json ]; then
            node scripts/seo/lighthouse-compare.mjs --old docs/lighthouse-baseline-prev.json --new docs/lighthouse-baseline-current.json || true
          fi

      - name: KPI Dashboard (optional Lab aggregation)
        working-directory: next-app
        run: node scripts/seo/kpi-dashboard.mjs || true

      - name: RUM Aggregate (falls vorhanden)
        working-directory: next-app
        run: |
          if [ -f docs/rum-metrics.jsonl ]; then node scripts/seo/rum-aggregate.mjs; fi

      - name: Threshold Gate (Lab + optional RUM)
        working-directory: next-app
        env:
          USE_RUM: '1'
        run: node scripts/seo/ci-threshold-gate.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perf-gate-artifacts
          path: |
            next-app/docs/lighthouse-baseline-*.json
            next-app/docs/lighthouse-diff.*
            next-app/docs/seo-kpi-dashboard.json
            next-app/docs/threshold-result.json
            next-app/docs/rum-summary.json
          if-no-files-found: ignore

      - name: Summary (Gate Result)
        if: always()
        run: |
          if [ -f next-app/docs/threshold-result.json ]; then
            echo '### Performance Gate Result' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '\nSchwellen & Status:' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat next-app/docs/threshold-result.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo 'Keine threshold-result.json gefunden' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Stop server
        if: always()
        run: |
          if [ -f next-app/server.pid ]; then kill $(cat next-app/server.pid) || true; fi
